server:
  port: ${PORT:8080}

spring:
  application:
    name: application.name=spring-boot-railway
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_railway?useTimezone=true&serverTimezone=UTC
    username: root
    password: aurora
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
logging:
  level:
   root: WARN
   deploy.railway.spring_boot_railway: DEBUG